name: technology_config
description: This plant produces electricity from tidal
technologies:
  oae:
    performance_model:
      model: OAEPerformanceModel
    finance_model:
      model: OAECostAndFinancialModel
    model_inputs:
      performance_parameters:
        number_ed_min: 1
        number_ed_max: 10
        max_ed_system_flow_rate_m3s: 0.02191  # m^3/s
        max_ed_system_power_w: 2844976 # W
        ed_acid_concentration: 0.9 # M
        ed_base_concentration: 0.7 # M
        frac_base_flow: 0.5714
        assumed_CDR_rate: 0.8  # mol CO2/mol NaOH
        use_storage_tanks: true
        initial_tank_volume_m3: 0.  # m^3
        store_hours: 12.  # hours
        acid_disposal_method: sell rca
        initial_salinity_ppt: 68.09  # ppt
        initial_temp_C: 18.0  # degrees Celsius
        initial_dic_mol_per_L: 0.0044  # mol/L
        initial_pH: 8.1  # initial pH
        save_outputs: true      
