name: driver_config
description: This analysis runs a tidal and wind power plant
general:
  folder_output: outputs
  # create_om_reports: true
# #### Design of Experiments Setup

driver:
  design_of_experiments:
    flag: true
    debug_print: true
    generator: csvgen
    filename: hybrid_input_cases.csv
  optimization:
    flag: false
    tol: 0.1
    max_iter: 100
    solver: COBYLA
    rhobeg: 5.
    debug_print: True
###### Design Variables
design_variables:
  tidal:
    rotor_radius:
      flag: true
      lower: 10 # m
      upper: 30 # m
      units: m
    device_rating:
      flag: true
      lower: 1115 # kW
      upper: 3345 # kW
      units: kW
    num_devices:
      flag: true
      lower: 15
      upper: 35
      units: unitless
  wind:
    num_turbines:
      flag: true
      lower: 15
      upper: 35
      units: unitless

#### Objective
objective:
  name: oae.carbon_credit_value
#   # Objective options
#   # finance_subgroup_electricity.LCOE for tidal
#   # finance_subgroup_oae_profast.LCOC
#   # oae.carbon_credit_value
recorder:
  file: cases.sql
  overwrite_recorder: true
  flag: true
  includes: ['*']
  # excludes: ['*resource_data']
