name: driver_config
description: This analysis runs a tidal power plant
general:
  folder_output: outputs
  # create_om_reports: true
# #### Design of Experiments Setup

driver:
  design_of_experiments:
    flag: false
    debug_print: true
    generator: csvgen
    filename: input_cases.csv
  optimization:
    flag: true
    tol: 0.1
    max_iter: 100
    solver: COBYLA
    rhobeg: 2.
    debug_print: True
###### Design Variables
design_variables:
  tidal:
    rotor_radius:
      flag: true
      lower: 5 # m
      upper: 50 # m
      units: m
    device_rating:
      flag: true
      lower: 1.115 # MW
      upper: 3.345 # MW
      units: MW

#### Objective
objective:
  name: finance_subgroup_electricity.LCOE
#   # Objective options
#   # finance_subgroup_electricity.LCOE for tidal
#   # finance_subgroup_oae_profast.LCOC
#   # oae.carbon_credit_value
recorder:
  file: cases.sql
  overwrite_recorder: true
  flag: true
  includes: ['*']
  # excludes: ['*resource_data']
