name: driver_config
description: This analysis runs a tidal power plant
general:
  folder_output: outputs
  # create_om_reports: true
# #### Design of Experiments Setup

driver:
  design_of_experiments:
    flag: true
    debug_print: true
    generator: csvgen
    filename: sensitivity_input_cases.csv
  optimization:
    flag: false
    tol: 0.1
    max_iter: 100
    solver: COBYLA
    rhobeg: 5.
    debug_print: True
###### Design Variables
design_variables:
  tidal:
    rotor_radius:
      flag: true
      lower: 10 # m
      upper: 30 # m
      units: m
    device_rating:
      flag: true
      lower: 2000 # kW
      upper: 6000 # kW
      units: kW
    power_coefficient:
      flag: true
      lower: 0.1
      upper: 0.7
      units: unitless
    mod_indep_X_exp:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_indep_Y_exp:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_indep_Z_exp:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_dep_X_exp:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_dep_Y_exp:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_dep_Z_exp:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_indep_alpha:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_indep_beta:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_indep_gamma:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_dep_alpha:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_dep_beta:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_dep_gamma:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_indep_initial_CapEx:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_indep_initial_OpEx:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_dep_initial_CapEx:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless
    mod_dep_initial_OpEx:
      flag: true
      lower: 0.7
      upper: 1.3
      units: unitless

#### Objective
objective:
  name: oae.carbon_credit_value
#   # Objective options
#   # finance_subgroup_electricity.LCOE for tidal
#   # finance_subgroup_oae_profast.LCOC
#   # oae.carbon_credit_value
recorder:
  file: cases.sql
  overwrite_recorder: true
  flag: true
  includes: ['*']
  # excludes: ['*resource_data']
